// This file is auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Run after any schema changes. Until your Supabase project is created,
// this placeholder keeps the app compilable.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      brands: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          website_url: string | null
          logo_url: string | null
          logo_bg_color: string | null
          is_indie: boolean
          country_of_origin: string | null
          price_tier: number | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          website_url?: string | null
          logo_url?: string | null
          logo_bg_color?: string | null
          is_indie?: boolean
          country_of_origin?: string | null
          price_tier?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['brands']['Insert']>
        Relationships: []
      }
      collections: {
        Row: {
          id: string
          brand_id: string
          name: string
          slug: string
          description: string | null
          release_year: number | null
          is_limited: boolean
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          name: string
          slug: string
          description?: string | null
          release_year?: number | null
          is_limited?: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['collections']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'collections_brand_id_fkey'
            columns: ['brand_id']
            isOneToOne: false
            referencedRelation: 'brands'
            referencedColumns: ['id']
          }
        ]
      }
      polishes: {
        Row: {
          id: string
          brand_id: string
          collection_id: string | null
          name: string
          slug: string
          description: string | null
          hex_color: string | null
          hex_secondary: string | null
          color_family: Database['public']['Enums']['color_family'] | null
          finish_category: Database['public']['Enums']['finish_category']
          finish_notes: string | null
          is_topper: boolean
          bottle_size_ml: number | null
          msrp_usd: number | null
          product_url: string | null
          is_discontinued: boolean
          is_limited: boolean
          images: string[]
          submitted_by: string | null
          is_verified: boolean
          dupe_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          collection_id?: string | null
          name: string
          slug: string
          description?: string | null
          hex_color?: string | null
          hex_secondary?: string | null
          color_family?: Database['public']['Enums']['color_family'] | null
          finish_category: Database['public']['Enums']['finish_category']
          finish_notes?: string | null
          is_topper?: boolean
          bottle_size_ml?: number | null
          msrp_usd?: number | null
          product_url?: string | null
          is_discontinued?: boolean
          is_limited?: boolean
          images?: string[]
          submitted_by?: string | null
          is_verified?: boolean
          dupe_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['polishes']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'polishes_brand_id_fkey'
            columns: ['brand_id']
            isOneToOne: false
            referencedRelation: 'brands'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'polishes_collection_id_fkey'
            columns: ['collection_id']
            isOneToOne: false
            referencedRelation: 'collections'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'polishes_submitted_by_fkey'
            columns: ['submitted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      tags: {
        Row: { id: string; name: string; slug: string }
        Insert: { id?: string; name: string; slug: string }
        Update: Partial<Database['public']['Tables']['tags']['Insert']>
        Relationships: []
      }
      polish_tags: {
        Row: { polish_id: string; tag_id: string }
        Insert: { polish_id: string; tag_id: string }
        Update: Partial<Database['public']['Tables']['polish_tags']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'polish_tags_polish_id_fkey'
            columns: ['polish_id']
            isOneToOne: false
            referencedRelation: 'polishes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'polish_tags_tag_id_fkey'
            columns: ['tag_id']
            isOneToOne: false
            referencedRelation: 'tags'
            referencedColumns: ['id']
          }
        ]
      }
      dupes: {
        Row: {
          id: string
          polish_a_id: string
          polish_b_id: string
          status: Database['public']['Enums']['dupe_status']
          submitted_by: string | null
          reviewed_by: string | null
          reviewed_at: string | null
          rejection_reason: string | null
          avg_color_accuracy: number | null
          avg_finish_accuracy: number | null
          avg_formula_accuracy: number | null
          avg_overall: number | null
          opinion_count: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          polish_a_id: string
          polish_b_id: string
          status?: Database['public']['Enums']['dupe_status']
          submitted_by?: string | null
          reviewed_by?: string | null
          reviewed_at?: string | null
          rejection_reason?: string | null
          avg_color_accuracy?: number | null
          avg_finish_accuracy?: number | null
          avg_formula_accuracy?: number | null
          avg_overall?: number | null
          opinion_count?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['dupes']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'dupes_polish_a_id_fkey'
            columns: ['polish_a_id']
            isOneToOne: false
            referencedRelation: 'polishes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'dupes_polish_b_id_fkey'
            columns: ['polish_b_id']
            isOneToOne: false
            referencedRelation: 'polishes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'dupes_submitted_by_fkey'
            columns: ['submitted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      dupe_opinions: {
        Row: {
          id: string
          dupe_id: string
          user_id: string
          color_accuracy: number
          finish_accuracy: number
          formula_accuracy: number
          color_notes: string | null
          finish_notes: string | null
          formula_notes: string | null
          owns_both: boolean
          helpful_votes: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          dupe_id: string
          user_id: string
          color_accuracy: number
          finish_accuracy: number
          formula_accuracy: number
          color_notes?: string | null
          finish_notes?: string | null
          formula_notes?: string | null
          owns_both?: boolean
          helpful_votes?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['dupe_opinions']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'dupe_opinions_dupe_id_fkey'
            columns: ['dupe_id']
            isOneToOne: false
            referencedRelation: 'dupes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'dupe_opinions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      opinion_votes: {
        Row: {
          opinion_id: string
          user_id: string
          is_helpful: boolean
          created_at: string
        }
        Insert: {
          opinion_id: string
          user_id: string
          is_helpful: boolean
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['opinion_votes']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'opinion_votes_opinion_id_fkey'
            columns: ['opinion_id']
            isOneToOne: false
            referencedRelation: 'dupe_opinions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'opinion_votes_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          role: Database['public']['Enums']['user_role']
          polish_count: number
          dupe_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          role?: Database['public']['Enums']['user_role']
          polish_count?: number
          dupe_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey'
            columns: ['id']
            isOneToOne: true
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      increment_dupe_count: {
        Args: { polish_id: string }
        Returns: undefined
      }
      decrement_dupe_count: {
        Args: { polish_id: string }
        Returns: undefined
      }
    }
    Enums: {
      finish_category:
        | 'cream'
        | 'shimmer'
        | 'glitter'
        | 'flakies'
        | 'duochrome'
        | 'multichrome'
        | 'holo'
        | 'magnetic'
        | 'jelly'
        | 'tinted'
        | 'matte'
        | 'satin'
        | 'topper'
        | 'other'
      color_family:
        | 'red'
        | 'orange'
        | 'yellow'
        | 'green'
        | 'blue'
        | 'purple'
        | 'pink'
        | 'neutral'
        | 'white'
        | 'black'
        | 'brown'
        | 'grey'
        | 'multicolor'
      dupe_status: 'pending' | 'approved' | 'rejected' | 'duplicate'
      user_role: 'user' | 'moderator' | 'admin'
    }
    CompositeTypes: Record<string, never>
  }
}
